version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: consultasdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  consultas-service:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=consultasdb

volumes:
  mysql_data:
