version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  imagenes-service:
    build: .
    ports:
      - "3003:80"
    depends_on:
      - mongo

volumes:
  mongo_data:
