version: '3'

services:
  pacientes:
    image: ms1_pacientes:latest
    container_name: pacientes
    ports:
      - "8000:8000"
    networks:
      - veterinaria_net

  consultas:
    image: ms2_consultas:latest
    container_name: consultas
    ports:
      - "3000:3000"
    networks:
      - veterinaria_net

  orquestador:
    build: .
    container_name: orquestador
    depends_on:
      - pacientes
      - consultas
    environment:
      - MS1_URL=http://pacientes:8000
      - MS2_URL=http://consultas:3000
    ports:
      - "8080:8080"
    networks:
      - veterinaria_net

networks:
  veterinaria_net:
    driver: bridge